### ISSUE TITLE
Non-sequential nonce ephemeric test failure

### ISSUE THREAD

**Issue by rafalkrupinski** [mmazi/rescu#106] opened 2018-03-02 13:26 UTC
si.mazi.rescu.RestInvocationHandlerTest#shouldReceiveSequentialNonces fails sometimes

**Comment by rafalkrupinski** [comment] 2018-03-02 13:30
From what I understand, this test checks whether the messages are sent in the same order as their nonces are generated, right?

**Comment by mmazi** [comment] 2018-03-02 14:42
The test checks that each nonce generated by the SynchronizedValueFactory that is passed to the API method (`nonce`) is higher than the previous nonce that was passed (`maxNonce`). The test seems rather badly written though (my bad). 

I can't reproduce the failure locally, though; and also don't see from the test log why the test failed e.g. [here](https://travis-ci.org/mmazi/rescu/builds/290318231) (expand the ./after-success.sh log at the bottom).

**Comment by rafalkrupinski** [comment] 2018-03-02 15:40
I couldn't reproduce it either until I've run it 300 times added 3x System.gc() or Thread.yeald() in the test method to introduce some delay.

Anyway, have a look at #107, give it a run (I've set up a daily build in travis on my fork) and let's see if the bug is fixed.

**Comment by mmazi** [comment] 2019-05-23 11:28
This seems to have been fixed in #107 (hasn't occurred since to my present knowledge).

**Closed as completed by mmazi** 2019-05-23 11:28 UTC
